# Generated by Django 5.2.8 on 2025-11-13 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_commune', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_incidentCat', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_province', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_affect', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('gerant', models.CharField(blank=True, max_length=50, null=True)),
                ('num_gerant', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_schoolCat', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_TypeInc', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_quartier', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_region', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=50)),
                ('dob_student', models.DateField()),
                ('add_student', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mather_name', models.CharField(max_length=50)),
                ('tutor_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('F', 'Faible'), ('M', 'Moyen'), ('G', 'Grave')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_incident', models.DateTimeField()),
                ('narration', models.TextField()),
                ('picture', models.JSONField(blank=True, default=list, null=True)),
                ('actionTaken', models.JSONField(blank=True, default=list)),
                ('cat_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.incidentcategory')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schoolcategory'),
        ),
        migrations.AddField(
            model_name='incidentcategory',
            name='typeIncident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typeincident'),
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ville', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ville'),
        ),
    ]
