# Generated by Django 5.2.8 on 2025-11-13 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeincident',
            name='code_TypeInc',
        ),
    ]
