# Generated by Django 5.2.8 on 2025-11-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_typeincident_code_typeinc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentcategory',
            name='code_incidentCat',
        ),
    ]
