# Generated by Django 5.2.8 on 2025-11-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_incidentcategory_code_incidentcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
