# Generated by Django 5.2.8 on 2025-11-24 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_incidentcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
            preserve_default=False,
        ),
    ]
