# Generated by Django 5.2.8 on 2025-11-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_school_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
