# Generated by Django 5.2.8 on 2025-11-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_incident_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='state',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
