# Generated by Django 5.2.8 on 2025-11-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_incident_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
