# Generated by Django 5.2.8 on 2025-12-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='actionTaken',
        ),
        migrations.AddField(
            model_name='incident',
            name='actions',
            field=models.ManyToManyField(related_name='incidents', to='core.action'),
        ),
    ]
